server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reservation
          uri: http://localhost:8072
          predicates:
            - Path=/reservations/**, 
        - id: notification
          uri: http://localhost:8073
          predicates:
            - Path=/notifications/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, /getUsers/**
        - id: store
          uri: http://localhost:8083
          predicates:
            - Path=/stores/**, 
        - id: authority
          uri: http://localhost:8084
          predicates:
            - Path=/authorities/**, 
        - id: recording
          uri: http://localhost:8085
          predicates:
            - Path=/storeUsings/**, /authorityChanings/**, /warnings/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "X-Total-Count"
              - "Link"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
            maxAge: 3600


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/stores/**, 
        - id: authority
          uri: http://authority:8080
          predicates:
            - Path=/authorities/**, 
        - id: recording
          uri: http://recording:8080
          predicates:
            - Path=/storeUsings/**, /authorityChanings/**, /warnings/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: alarmpbcfe
          uri: http://alarmpbcfe:8080
          predicates:
            - Path=/alarmpbcfe/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "X-Total-Count"
              - "Link"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
            maxAge: 3600

server:
  port: 8080
